# Database Credentials
db.driverName = com.mysql.cj.jdbc.Driver
db.connectionString = jdbc:mysql://database-1.czi640q8khnh.ap-southeast-1.rds.amazonaws.com:3306/shopping-cart
db.username = admin
db.password = Q8UAnirkx2jKWrjNHJmB

#Mailer Credentials
mailer.email=san.011295@gmail.com
mailer.password=wzfu jots fgux zsyp
